---
all:
  children:
    windows:
      vars:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_port: 5985
        ansible_winrm_transport: ntlm
        scripts_path: "C:\\Perflogs\\roblox"
        password_manager_ip: "10.1.1.10"
        siem_IP: "" #REPLACE
        siem_name: "Grafana"
        birdsnest_host_ip: "10.1.1.10"
        birdsnest_host: "10.1.1.10:1738"
        birdsnest_token: "1248365c7893"
        winrm_ip: "" #REPLACE
      children:
        win_10_1_1_5:
          vars:
            ansible_user: "Administrator"
            ansible_password: "Password-123456"
            scored_services: "httpsio"
            is_win_server: "true"
            is_server_core: "false"
            server_type: "adfs"
          hosts:
            10.1.1.5:
        