---
- name: "WIN - Minimal Facts"
  hosts: windows
  gather_facts: false

  tasks:
    - name: Gather minimal Windows facts
      setup:
        filter:
          - ansible_hostname
          - ansible_os_family

- name: "WIN - Copy Core Scripts"
  hosts: windows
  gather_facts: false
  roles:
    - copy-core-scripts
  tags:
    - windows
    - copy
    - never

- name: "WIN - Run Downloads Script"
  hosts: windows
  gather_facts: false
  roles:
    - download
  tags:
    - windowsOld
    - download
    - never

- name: "WIN - Run Core Scripts"
  hosts: windows
  gather_facts: false
  roles:
    - run-core-scripts
  tags:
    - windows
    - windowsOld
    - backup
    - firewall
    - never
  ignore_errors: true

- name: "WIN - Copy Scripts and Tools"
  hosts: windows
  gather_facts: false
  roles:
    - copy-other
  tags:
    - windows
    - copy
    - never
  ignore_errors: true

- name: "WIN - Distributed Backups"
  hosts: windows
  gather_facts: false
  roles:
    - adv-backup
  tags:
    - winAdvBackup
  ignore_errors: true

- name: "WIN - Setup Password Manager Client"
  hosts: windows
  gather_facts: false
  roles:
    - password-manager-client
  tags:
    - windows
    - windows_old
    - password
    - password_manager
    - never
  ignore_errors: true

- name: "WIN - Logging"
  hosts: windows
  gather_facts: false
  roles:
    - logging
  tags:
    - windows
    - windowsOld
    - logging
    - never
  ignore_errors: true

- name: "WIN - Inventory"
  hosts: windows
  gather_facts: false
  roles:
    - inventory
  tags:
    - windows
    - windowsOld
    - inventory
    - never
  ignore_errors: true

- name: "WIN - Audit"
  hosts: windows  
  gather_facts: false
  roles:
    - audit
  tags:
    - windows
    - windowsOld
    - audit
    - never
  ignore_errors: true